name: Code Compiles. page.tsx renders.

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

defaults:
  run:
    working-directory: ./tables4u

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '18'
    - run: npm ci
    - run: npm run build
    - run: npm run test